# Generated by Django 4.0.5 on 2022-07-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTitle', models.CharField(max_length=250)),
                ('albumTrack', models.CharField(max_length=250)),
                ('trackDuration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singletitle', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Albums',
        ),
        migrations.DeleteModel(
            name='AlbumTrack',
        ),
        migrations.DeleteModel(
            name='NewReleases',
        ),
        migrations.DeleteModel(
            name='Singles',
        ),
    ]
