# Generated by Django 4.0.5 on 2022-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_album_newrelease_single_delete_albums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTitle', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='albumTitle',
        ),
    ]
