# Generated by Django 4.0.5 on 2022-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_albumlist_remove_album_albumtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='logo',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
    ]
