# Generated by Django 4.0.5 on 2022-07-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_newrelease_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='song',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
    ]
