# Generated by Django 4.0.5 on 2022-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_newrelease_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrelease',
            old_name='song',
            new_name='NewSong',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='album',
            name='zipfile',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='single',
            name='single',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
    ]
