# Generated by Django 4.0 on 2022-07-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_song_newrelease_newsong_album_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumName',
            field=models.CharField(max_length=250, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
    ]
