# Generated by Django 4.0 on 2022-07-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_album_albumname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='albumTrack',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='album',
            name='trackDuration',
        ),
    ]
