# Generated by Django 4.0 on 2022-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='albumName',
        ),
        migrations.RemoveField(
            model_name='album',
            name='zipfile',
        ),
        migrations.AddField(
            model_name='sub',
            name='albumName',
            field=models.CharField(max_length=250, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='sub',
            name='zipfile',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
    ]
