# Generated by Django 4.0 on 2022-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_sub_albumname_remove_sub_zipfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='zipfile',
            new_name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='albumTrack',
            field=models.CharField(max_length=250, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='album',
            name='trackDuration',
            field=models.CharField(max_length=10, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='albumlist',
            name='zipfile',
            field=models.FileField(null=b'I00\n', upload_to=''),
            preserve_default=b'I00\n',
        ),
    ]
