# Generated by Django 4.0 on 2022-07-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_album_albumname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumTrack',
            field=models.ForeignKey(max_length=250, null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to='myapp.albumlist'),
        ),
    ]
