# Generated by Django 4.0 on 2022-07-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_album_albumtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumTrack',
            field=models.CharField(max_length=250, null=b'I00\n'),
        ),
    ]
