# Generated by Django 4.0 on 2022-08-02 21:30

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_album_albumtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumlist',
            field=models.ForeignKey(null=b'I00\n', on_delete=builtins.callable, to='myapp.albumlist'),
            preserve_default=b'I00\n',
        ),
    ]
