# Generated by Django 4.0 on 2022-08-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_album_albumlist_albumlist_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumlist',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='albumlist',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to='myapp.albumlist'),
            preserve_default=b'I00\n',
        ),
    ]
