# Generated by Django 4.0 on 2022-08-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_album_albumsongs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumlist',
            old_name='zipfile',
            new_name='albumzip',
        ),
    ]
