# Generated by Django 4.2.2 on 2023-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_albumlist_albumart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrelease',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='single',
            name='duration',
        ),
        migrations.AddField(
            model_name='newrelease',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='single',
            name='download',
            field=models.IntegerField(default=0),
        ),
    ]
