# Generated by Django 4.2.2 on 2023-06-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_newrelease_duration_remove_single_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single',
            name='download',
        ),
        migrations.AddField(
            model_name='single',
            name='duration',
            field=models.CharField(max_length=10, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
    ]
